export type Subject = {
  id: string;
  name: string;
  color: string;
};

export type EventType = 'course' | 'kholle' | 'ds' | 'dm' | 'study' | 'other';

export type Event = {
  id: string;
  title: string;
  subjectId: string;
  type: EventType;
  startTime: string; // ISO string
  endTime: string; // ISO string
  location?: string;
  description?: string;
  recurrence?: {
    frequency: 'daily' | 'weekly';
    daysOfWeek?: number[]; // 0-6 for Sunday-Saturday
    endDate?: string; // ISO string
  };
  isCompleted?: boolean;
};

export type Assignment = {
  id: string;
  title: string;
  subjectId: string;
  type: 'dm' | 'other';
  description?: string;
  dueDate: string; // ISO string
  priority: 'low' | 'medium' | 'high';
  status: 'pending' | 'in-progress' | 'completed';
  estimatedHours: number;
  relatedEvents?: string[]; // IDs of related events (e.g., study sessions)
};

export type StudySession = {
  id: string;
  title: string;
  subjectId: string;
  relatedToId?: string; // ID of related event or assignment
  startTime: string; // ISO string
  endTime: string; // ISO string
  priority: 'low' | 'medium' | 'high';
  autoGenerated: boolean; // whether it was created by the AI
  isCompleted: boolean;
};

export type Notification = {
  id: string;
  title: string;
  message: string;
  type: 'info' | 'warning' | 'error' | 'success';
  timestamp: string; // ISO string
  read: boolean;
  relatedItemId?: string; // ID of related event, assignment, etc.
};

export type WorkloadDay = {
  date: string; // ISO date string
  load: number; // 0-100 workload percentage
};

export type UserPreferences = {
  studyPreferences: {
    preferredStudyHours: number[]; // 0-23 preferred hours of day
    studyDuration: number; // in minutes
    breakDuration: number; // in minutes
    studySessionsPerDay: number;
  };
  notificationSettings: {
    enableNotifications: boolean;
    remindBeforeDeadline: number; // in hours
    remindBeforeEvent: number; // in minutes
  };
  themePreference: 'light' | 'dark' | 'system';
};