import { v4 as uuidv4 } from 'uuid';
import { 
  Event, 
  StudySession, 
  Subject, 
  UserPreferences 
} from '../types';
import { 
  addDays, 
  subDays, 
  parseISO, 
  addMinutes, 
  isAfter, 
  isBefore, 
  isSameDay,
  differenceInDays,
  setHours,
  setMinutes,
  format,
  getHours
} from 'date-fns';

// Function to check if a time slot is available
const isTimeSlotAvailable = (
  startTime: Date,
  endTime: Date,
  events: Event[],
  studySessions: StudySession[]
): boolean => {
  // Check against existing events
  for (const event of events) {
    const eventStart = parseISO(event.startTime);
    const eventEnd = parseISO(event.endTime);
    
    if (
      (isAfter(startTime, eventStart) && isBefore(startTime, eventEnd)) ||
      (isAfter(endTime, eventStart) && isBefore(endTime, eventEnd)) ||
      (isBefore(startTime, eventStart) && isAfter(endTime, eventEnd)) ||
      (isSameDay(startTime, eventStart) && getHours(startTime) === getHours(eventStart))
    ) {
      return false;
    }
  }
  
  // Check against existing study sessions
  for (const session of studySessions) {
    const sessionStart = parseISO(session.startTime);
    const sessionEnd = parseISO(session.endTime);
    
    if (
      (isAfter(startTime, sessionStart) && isBefore(startTime, sessionEnd)) ||
      (isAfter(endTime, sessionStart) && isBefore(endTime, sessionEnd)) ||
      (isBefore(startTime, sessionStart) && isAfter(endTime, sessionEnd)) ||
      (isSameDay(startTime, sessionStart) && getHours(startTime) === getHours(sessionStart))
    ) {
      return false;
    }
  }
  
  return true;
};

// Find the best time slot for a study session
const findBestTimeSlot = (
  date: Date,
  duration: number,
  events: Event[],
  studySessions: StudySession[],
  preferences: UserPreferences
): { start: Date; end: Date } | null => {
  const { preferredStudyHours } = preferences.studyPreferences;
  
  // Sort preferred hours to prioritize them
  const sortedHours = [...preferredStudyHours].sort();
  
  // Try each preferred hour
  for (const hour of sortedHours) {
    const startTime = setHours(setMinutes(date, 0), hour);
    const endTime = addMinutes(startTime, duration);
    
    if (isTimeSlotAvailable(startTime, endTime, events, studySessions)) {
      return { start: startTime, end: endTime };
    }
  }
  
  // If no preferred hours work, try other hours
  for (let hour = 8; hour < 22; hour++) {
    if (preferredStudyHours.includes(hour)) continue; // Skip already checked hours
    
    const startTime = setHours(setMinutes(date, 0), hour);
    const endTime = addMinutes(startTime, duration);
    
    if (isTimeSlotAvailable(startTime, endTime, events, studySessions)) {
      return { start: startTime, end: endTime };
    }
  }
  
  return null;
};

// Generate study sessions for an event
export const generateStudySessions = (
  event: Event,
  subject: Subject,
  events: Event[],
  existingStudySessions: StudySession[],
  preferences: UserPreferences,
  estimatedHours?: number
): StudySession[] => {
  const result: StudySession[] = [];
  const eventDate = parseISO(event.startTime);
  const now = new Date();
  
  // If the event is in the past, don't generate sessions
  if (isBefore(eventDate, now)) {
    return [];
  }
  
  const { studyDuration } = preferences.studyPreferences;
  
  // For DS and kholles, we'll generate multiple study sessions
  if (event.type === 'ds' || event.type === 'kholle') {
    // Determine how many days before the event to start studying
    const daysBeforeEvent = event.type === 'ds' ? 7 : 3;
    
    // Calculate how many study sessions to generate
    const numberOfSessions = event.type === 'ds' ? 4 : 2;
    
    // Generate sessions distributed over the days before the event
    for (let i = 0; i < numberOfSessions; i++) {
      // Distribute sessions evenly before the event
      const daysOffset = Math.floor((daysBeforeEvent * (numberOfSessions - i)) / numberOfSessions);
      const sessionDate = subDays(eventDate, daysOffset);
      
      // Skip if the date is in the past
      if (isBefore(sessionDate, now)) {
        continue;
      }
      
      // Find a suitable time slot
      const timeSlot = findBestTimeSlot(
        sessionDate,
        studyDuration,
        events,
        [...existingStudySessions, ...result],
        preferences
      );
      
      if (timeSlot) {
        const priority = i === numberOfSessions - 1 ? 'high' : 'medium';
        const sessionTitle = `Révision: ${subject.name} (${format(timeSlot.start, 'PPP')})`;
        
        result.push({
          id: uuidv4(),
          title: sessionTitle,
          subjectId: subject.id,
          relatedToId: event.id,
          startTime: timeSlot.start.toISOString(),
          endTime: timeSlot.end.toISOString(),
          priority,
          autoGenerated: true,
          isCompleted: false
        });
      }
    }
  } 
  // For DMs, generate sessions based on estimated work time
  else if (event.type === 'dm') {
    const hoursToSpend = estimatedHours ?? 2;

    // Calculate how many study sessions are needed based on preferred session duration
    const sessionDurationHours = studyDuration / 60;
    let numberOfSessions = Math.ceil(hoursToSpend / sessionDurationHours);

    // Days available until the deadline
    const daysUntilDeadline = Math.max(differenceInDays(eventDate, now), 1);

    // Avoid generating more sessions than days available
    numberOfSessions = Math.min(numberOfSessions, daysUntilDeadline);
    
    // Generate sessions distributed over days
    for (let i = 0; i < numberOfSessions; i++) {
      // If multiple sessions, distribute them
      const daysOffset = Math.floor((daysUntilDeadline * (numberOfSessions - i)) / numberOfSessions);
      const sessionDate = subDays(eventDate, daysOffset);
      
      // Find a suitable time slot
      const timeSlot = findBestTimeSlot(
        sessionDate,
        studyDuration,
        events,
        [...existingStudySessions, ...result],
        preferences
      );
      
      if (timeSlot) {
        const priority = i === numberOfSessions - 1 ? 'high' : 'medium';
        const sessionTitle = `Travail DM: ${subject.name} (${format(timeSlot.start, 'PPP')})`;
        
        result.push({
          id: uuidv4(),
          title: sessionTitle,
          subjectId: subject.id,
          relatedToId: event.id,
          startTime: timeSlot.start.toISOString(),
          endTime: timeSlot.end.toISOString(),
          priority,
          autoGenerated: true,
          isCompleted: false
        });
      }
    }
  }
  
  return result;
};